version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"

  product-service:
    build: ./product-service
    ports:
      - "5002:5002"

  order-service:
    build: ./order-service
    ports:
      - "5003:5003"

